modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/FireBall1725/DevWorld2/issues"

[[mods]]
modId="devworld2"
version="${file.jarVersion}"
displayName="DevWorld 2"
displayURL="https://github.com/FireBall1725/DevWorld2"
authors="FireBall1725"
description="DevWorld2 is a simple mod used to create a flat world with pre-defined settings for the world to quickly create a world for testing a mod that you are developing."

[[dependencies.devworld2]]
  modId="forge"
  mandatory=true
  versionRange="[31,)"
  ordering="NONE"
  side="CLIENT"

[[dependencies.devworld2]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.15.2]"
  ordering="NONE"
  side="CLIENT"
