version: 2
jobs:
  version:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: get new version
          command: |
            export NEW_VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version)
            echo $NEW_VERSION > CI_VERSION
            echo $NEW_VERSION
      - persist_to_workspace:
          root: .
          paths:
            - CI_VERSION

  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Build"
          command: |
            export CI_VERSION=`cat CI_VERSION`
            ./gradlew build
      - store_artifacts:
          path: build/libs
          destination: artifact-file

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  build_publish:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            export CI_VERSION=`cat CI_VERSION`
      - run:
          name: "Publish Release"
          command: |
            export CI_VERSION=`cat CI_VERSION`
            ./gradlew build generateChangelogs
            ./gradlew githubRelease publishGithubPublicationToGithubRepository # artifactorypublish curseforge
workflows:
  version: 2
  main:
    jobs:
      - version
      - build:
          filters:
            branches:
              ignore:
                - master
          requires:
            - version
      - build_publish:
          filters:
            branches:
              only:
                - master
          requires:
            - version